using Dominatus.Actuators.HomeAssistant;
using Dominatus.Actuators.Standard;
using Dominatus.Actuators.Standard.Calendar;
using Dominatus.Core.Blackboard;
using Dominatus.Core.Hfsm;
using Dominatus.Core.Nodes;
using Dominatus.Core.Nodes.Steps;
using Dominatus.Core.Runtime;
using Dominatus.Server;

Console.WriteLine("Dominatus release package smoke");

var workspace = Path.Combine(Path.GetTempPath(), "dominatus-release-smoke", Guid.NewGuid().ToString("N"));
Directory.CreateDirectory(workspace);

try
{
    var host = new ActuatorHost();
    var world = new AiWorld(host);

    host.RegisterStandardFileActuators(new SandboxedFileActuatorOptions { Roots = [new SandboxedFileRoot("workspace", workspace)] });
    host.RegisterStandardTimeActuators();
    host.RegisterStandardCalendarActuators(new CalendarActuatorOptions { Roots = [new SandboxedFileRoot("workspace", workspace)] });

    var graph = new HfsmGraph { Root = "Root" };
    graph.Add(new HfsmStateDef { Id = "Root", Node = static _ => Idle() });

    var agent = new AiAgent(new HfsmInstance(graph));
    world.Add(agent);
    var ctx = new AiCtx(world, agent, agent.Events, CancellationToken.None, world.View, world.Mail, world.Actuator);

    var agentReady = new BbKey<bool>("agent.ready");
    var ttlKey = new BbKey<string>("agent.ttl");
    var worldReady = new BbKey<bool>("world.ready");

    agent.Bb.Set(agentReady, true);
    agent.Bb.SetFor(ttlKey, "ttl", world.Clock.Time, 1.0f);
    agent.Bb.Expire(world.Clock.Time + 2f);
    world.Bb.Set(worldReady, true);

    var writeResult = host.Dispatch(ctx, new WriteCalendarEventCommand(
        "workspace",
        "calendar/release-smoke.ics",
        new CalendarEventSpec(Guid.NewGuid().ToString("N"), "Dominatus release smoke", DateTimeOffset.UtcNow, DateTimeOffset.UtcNow.AddMinutes(10), "Generated by package smoke.", "local")));
    Require(writeResult.Ok, "Calendar write should succeed.");

    var readResult = host.Dispatch(ctx, new ReadTextFileCommand("workspace", "calendar/release-smoke.ics"));
    Require(readResult.Ok, "Calendar read should succeed.");
    Require(readResult.Payload is string ics && ics.Contains("BEGIN:VCALENDAR", StringComparison.Ordinal), "ICS output should contain VCALENDAR header.");

    var runtime = new DominatusServerRuntime(world);
    var isWorldReady = runtime.Read(w => w.Bb.GetOrDefault(worldReady, false));
    Require(isWorldReady, "DominatusServerRuntime.Read should return expected world blackboard value.");

    var projectText = File.ReadAllText(Path.Combine(Directory.GetCurrentDirectory(), "tests/Dominatus.Release.PackageSmoke/Dominatus.Release.PackageSmoke.csproj"));
    Require(!projectText.Contains("<ProjectReference", StringComparison.OrdinalIgnoreCase), "Release smoke project must use PackageReference only.");

    var homeAssistantOptions = new HomeAssistantActuatorOptions
    {
        BaseUri = new Uri("http://localhost:8123"),
        AccessToken = "fake-token",
        AllowedEntities = ["light.demo"],
        AllowedServices = [new AllowedHomeAssistantService("light", "turn_on", ["light.demo"])]
    };
    _ = homeAssistantOptions;

    Console.WriteLine("Dominatus release package smoke: OK");
    return 0;
}
finally
{
    if (Directory.Exists(workspace)) Directory.Delete(workspace, recursive: true);
}

static void Require(bool condition, string message)
{
    if (!condition) throw new InvalidOperationException(message);
}

static IEnumerator<AiStep> Idle()
{
    yield break;
}
