using System.Text.Json;
using Dominatus.Actuators.Audio;
using Dominatus.Core.Hfsm;
using Dominatus.Core.Runtime;

public sealed class AudioTests
{
    [Fact] public void AudioProviderRegistry_RejectsDuplicateProviders() { var r = new AudioProviderRegistry().Register(new FakeAudioProvider("fake")); Assert.Throws<InvalidOperationException>(() => r.Register(new FakeAudioProvider("FAKE"))); }
    [Fact] public void AudioProviderRegistry_GetsProviderCaseInsensitive() { var p = new FakeAudioProvider("fake"); Assert.Same(p, new AudioProviderRegistry().Register(p).GetRequired("FAKE")); }
    [Fact] public void TextToSpeechCommand_RequiresProvider() => Assert.Throws<ArgumentException>(() => AudioValidation.Validate(Tts() with { ProviderId = "" }));
    [Fact] public void TextToSpeechCommand_RequiresIdempotencyKey() => Assert.Throws<ArgumentException>(() => AudioValidation.Validate(Tts() with { IdempotencyKey = "" }));
    [Fact] public void TextToSpeechCommand_RequiresText() => Assert.Throws<ArgumentException>(() => AudioValidation.Validate(Tts() with { Text = "" }));
    [Fact] public void TextToSpeechCommand_RequiresOutputPath() => Assert.Throws<ArgumentException>(() => AudioValidation.Validate(Tts() with { OutputPath = "" }));
    [Fact] public void MetadataPolicy_DefaultWritesSidecarButNotInputText() { var p = new AudioMetadataPolicy(); Assert.True(p.WriteSidecarJson); Assert.False(p.IncludeInputTextInMetadata); Assert.True(p.IncludeTextHash); Assert.False(p.EmbedOpenFileMetadata); }
    [Fact] public async Task FakeAudioProvider_TextToSpeech_WritesValidWav() { var res = await Provider().TextToSpeechAsync(Tts(), default); AssertWav(res.Artifact.Path); }
    [Fact] public async Task FakeAudioProvider_TextToSpeech_WritesSidecarMetadata() { var res = await Provider().TextToSpeechAsync(Tts(), default); Assert.True(File.Exists(res.Artifact.MetadataPath)); }
    [Fact] public async Task FakeAudioProvider_TextToSpeech_MetadataIncludesTextHashButNotTextByDefault() { var res = await Provider().TextToSpeechAsync(Tts() with { Text = "secret words" }, default); var json = File.ReadAllText(res.Artifact.MetadataPath!); Assert.Contains("textSha256", json); Assert.DoesNotContain("secret words", json); }
    [Fact] public async Task FakeAudioProvider_TextToSpeech_CanIncludeInputTextWhenPolicyAllows() { var res = await Provider().TextToSpeechAsync(Tts() with { Text = "include me", MetadataPolicy = new() { IncludeInputTextInMetadata = true } }, default); Assert.Contains("include me", File.ReadAllText(res.Artifact.MetadataPath!)); }
    [Fact] public async Task FakeAudioProvider_SoundEffect_WritesValidWav() { var res = await Provider().GenerateSoundEffectAsync(Sfx(), default); AssertWav(res.Artifact.Path); }
    [Fact] public async Task FakeAudioProvider_Idempotency_RepeatedSameKeyReturnsSameResult() { var p = Provider(); var c = Tts(); var a = await p.TextToSpeechAsync(c, default); var b = await p.TextToSpeechAsync(c, default); Assert.Equal(a.Artifact.Path, b.Artifact.Path); Assert.True(b.FromCache); }
    [Fact] public async Task FakeAudioProvider_Idempotency_ConflictingPayloadFails() { var p = Provider(); await p.TextToSpeechAsync(Tts(), default); await Assert.ThrowsAsync<InvalidOperationException>(async () => await p.TextToSpeechAsync(Tts() with { Text = "different" }, default)); }
    [Fact] public void AudioActuationHandler_DispatchesTextToSpeech() { var (host, ctx) = Ctx(); var res = host.Dispatch(ctx, Tts()); Assert.True(res.Ok); Assert.IsType<TextToSpeechResult>(res.Payload); }
    [Fact] public void AudioActuationHandler_DispatchesSoundEffect() { var (host, ctx) = Ctx(); var res = host.Dispatch(ctx, Sfx()); Assert.True(res.Ok); Assert.IsType<GenerateSoundEffectResult>(res.Payload); }
    [Fact] public void AudioActuationHandler_UnknownProviderFailsSafely() { var (host, ctx) = Ctx(); var res = host.Dispatch(ctx, Tts() with { ProviderId = "missing" }); Assert.False(res.Ok); Assert.Contains("Unknown audio provider", res.Error); }
    [Fact] public void AudioErrors_DoNotLeakSecrets() { var error = AudioActuationHandler.Sanitize(new InvalidOperationException("bad sk-secret api_key token")); Assert.DoesNotContain("sk-secret", error); Assert.DoesNotContain("api_key", error); }
    [Fact] public async Task NoHiddenFingerprinting_MetadataStatesNoDominatusHiddenWatermark() { var res = await Provider().TextToSpeechAsync(Tts(), default); using var doc = JsonDocument.Parse(File.ReadAllText(res.Artifact.MetadataPath!)); Assert.False(doc.RootElement.GetProperty("hiddenWatermarkAddedByDominatus").GetBoolean()); }
    [Fact] public void Package_HasNoElevenLabsOpenAiQwenProviderDependenciesInM0() { var csproj = File.ReadAllText(Path.Combine(Root(), "src/Dominatus.Actuators.Audio/Dominatus.Actuators.Audio.csproj")); Assert.DoesNotContain("Eleven", csproj); Assert.DoesNotContain("OpenAI", csproj); Assert.DoesNotContain("Qwen", csproj); }
    private static FakeAudioProvider Provider() => new();
    private static string Tmp(string name) => Path.Combine(Path.GetTempPath(), "dominatus-audio-tests", Guid.NewGuid().ToString("N"), name);
    private static TextToSpeechCommand Tts() => new() { ProviderId = "fake", IdempotencyKey = "key", Text = "hello", OutputPath = Tmp("out.wav") };
    private static GenerateSoundEffectCommand Sfx() => new() { ProviderId = "fake", IdempotencyKey = "sfx", Prompt = "zap", OutputPath = Tmp("sfx.wav"), DurationSeconds = .25 };
    private static void AssertWav(string path) { var b = File.ReadAllBytes(path); Assert.Equal((byte)'R', b[0]); Assert.Equal((byte)'I', b[1]); Assert.Equal((byte)'F', b[2]); Assert.Equal((byte)'F', b[3]); Assert.Equal((byte)'W', b[8]); Assert.Equal((byte)'A', b[9]); Assert.Equal((byte)'V', b[10]); Assert.Equal((byte)'E', b[11]); }
    private static (ActuatorHost, AiCtx) Ctx() { var host = new ActuatorHost().RegisterAudioActuators(new AudioProviderRegistry().Register(new FakeAudioProvider())); var world = new AiWorld(host); var agent = new AiAgent(new HfsmInstance(new HfsmGraph { Root = "root" })); world.Add(agent); return (host, new AiCtx(world, agent, agent.Events, default, world.View, world.Mail, host, new LiveWorldBb(world.Bb))); }
    private static string Root() { var d = new DirectoryInfo(AppContext.BaseDirectory); while (d is not null && !File.Exists(Path.Combine(d.FullName, "Dominatus.slnx"))) d = d.Parent; return d!.FullName; }
}

public sealed class ElevenLabsAudioProviderTests
{
    [Fact] public void ElevenLabsOptions_ToString_DoesNotLeakApiKey() { var s = Options().ToString(); Assert.DoesNotContain("super-secret", s); Assert.Contains("ApiKey = ***", s); }
    [Fact] public async Task ElevenLabsProvider_TextToSpeech_MapsVoiceModelAndText() { var fake = new FakeElevenLabsClient(); await Provider(fake).TextToSpeechAsync(Tts(), default); Assert.Equal("voice-1", fake.Request!.VoiceId); Assert.Equal("hello eleven", fake.Request.Text); Assert.Equal("eleven_multilingual_v2", fake.Request.ModelId); }
    [Fact] public async Task ElevenLabsProvider_TextToSpeech_SendsXiApiKeyHeaderViaClientOptions() { using var handler = new CaptureHandler(); var p = new ElevenLabsAudioProvider(Options() with { BaseUri = new Uri("https://example.test") }, new HttpClient(handler)); await p.TextToSpeechAsync(Tts(), default); Assert.Equal("super-secret", handler.ApiKey); Assert.Contains("output_format=mp3_44100_128", handler.Uri!.Query); Assert.Contains("enable_logging=true", handler.Uri.Query); }
    [Fact] public async Task ElevenLabsProvider_TextToSpeech_MapsOutputFormatToMp3Artifact() { var res = await Provider(new()).TextToSpeechAsync(Tts(), default); Assert.Equal(AudioFormat.Mp3, res.Artifact.Format); Assert.Equal("audio/mpeg", res.Artifact.MimeType); Assert.Equal(44100, res.Artifact.SampleRateHz); }
    [Fact] public async Task ElevenLabsProvider_TextToSpeech_WritesReturnedAudioBytes() { var fake = new FakeElevenLabsClient { AudioBytes = new byte[] { 1, 2, 3, 4 } }; var cmd = Tts(); await Provider(fake).TextToSpeechAsync(cmd, default); Assert.Equal(fake.AudioBytes, File.ReadAllBytes(cmd.OutputPath)); }
    [Fact] public async Task ElevenLabsProvider_TextToSpeech_WritesSidecarMetadata() { var res = await Provider(new()).TextToSpeechAsync(Tts(), default); Assert.True(File.Exists(res.Artifact.MetadataPath)); }
    [Fact] public async Task ElevenLabsProvider_TextToSpeech_MetadataIncludesProviderModelVoiceAndNoHiddenWatermark() { var res = await Provider(new()).TextToSpeechAsync(Tts(), default); var json = File.ReadAllText(res.Artifact.MetadataPath!); Assert.Contains("elevenlabs", json); Assert.Contains("eleven_multilingual_v2", json); Assert.Contains("voice-1", json); Assert.Contains("hiddenWatermarkAddedByDominatus", json); }
    [Fact] public async Task ElevenLabsProvider_TextToSpeech_DoesNotStoreInputTextByDefault() { var res = await Provider(new()).TextToSpeechAsync(Tts() with { Text = "secret input text" }, default); Assert.DoesNotContain("secret input text", File.ReadAllText(res.Artifact.MetadataPath!)); }
    [Fact] public async Task ElevenLabsProvider_TextToSpeech_CanStoreInputTextWhenPolicyAllows() { var res = await Provider(new()).TextToSpeechAsync(Tts() with { Text = "ok to store", MetadataPolicy = new() { IncludeInputTextInMetadata = true } }, default); Assert.Contains("ok to store", File.ReadAllText(res.Artifact.MetadataPath!)); }
    [Fact] public async Task ElevenLabsProvider_TextToSpeech_RejectsOutputExtensionMismatch() => await Assert.ThrowsAsync<ArgumentException>(async () => await Provider(new()).TextToSpeechAsync(Tts() with { OutputPath = Tmp("out.wav"), PreferredFormat = AudioFormat.Mp3 }, default));
    [Fact] public async Task ElevenLabsProvider_TextToSpeech_RedactsApiKeyInErrors() { var ex = await Assert.ThrowsAsync<InvalidOperationException>(async () => await Provider(new FakeElevenLabsClient { Exception = new ElevenLabsApiException(System.Net.HttpStatusCode.BadRequest, "/v1/text-to-speech/{voice_id}", "req", "bad xi-api-key: super-secret token abc") }, Options() with { IncludeRawProviderErrors = true }).TextToSpeechAsync(Tts(), default)); Assert.DoesNotContain("super-secret", ex.Message); Assert.DoesNotContain("abc", ex.Message); }
    [Fact] public async Task ElevenLabsProvider_GenerateSoundEffect_ReturnsUnsupported() => await Assert.ThrowsAsync<NotSupportedException>(async () => await Provider(new()).GenerateSoundEffectAsync(new GenerateSoundEffectCommand { ProviderId = "elevenlabs", IdempotencyKey = "sfx", Prompt = "zap", OutputPath = Tmp("sfx.wav") }, default));
    [Fact] public void ElevenLabsOutputFormatMapper_InfersMp3() { var info = ElevenLabsOutputFormatMapper.Infer("mp3_44100_128"); Assert.Equal(AudioFormat.Mp3, info.Format); Assert.Equal(".mp3", info.Extension); Assert.Equal(44100, info.SampleRateHz); }
    [Fact] public void ElevenLabsOutputFormatMapper_RejectsUnsupportedRawPcmAsWavUnlessWrapped() { var info = ElevenLabsOutputFormatMapper.Infer("pcm_16000"); Assert.Throws<ArgumentException>(() => ElevenLabsOutputFormatMapper.ValidateExtension("out.wav", info)); Assert.Equal(AudioFormat.Unknown, info.Format); }
    [Fact] public void AudioPackage_HasNoElevenLabsSdkDependency() { var csproj = File.ReadAllText(Path.Combine(Root(), "src/Dominatus.Actuators.Audio/Dominatus.Actuators.Audio.csproj")); Assert.DoesNotContain("ElevenLabs", csproj); Assert.DoesNotContain("Eleven", csproj); }
    [Fact] public void ElevenLabsLive_TextToSpeech_SkippedByDefault() { if (Environment.GetEnvironmentVariable("DOMINATUS_ELEVENLABS_LIVE_TESTS") == "1") return; Assert.NotEqual("1", Environment.GetEnvironmentVariable("DOMINATUS_ELEVENLABS_LIVE_TESTS")); }

    private static ElevenLabsAudioProvider Provider(FakeElevenLabsClient client, ElevenLabsAudioProviderOptions? options = null) => new(options ?? Options(), client);
    private static ElevenLabsAudioProviderOptions Options() => new() { ApiKey = "super-secret" };
    private static TextToSpeechCommand Tts() => new() { ProviderId = "elevenlabs", IdempotencyKey = "tts-key", Text = "hello eleven", Voice = new VoiceRef { VoiceId = "voice-1", DisplayName = "Voice", SourceKind = VoiceSourceKind.Licensed, ProviderId = "elevenlabs" }, ModelId = null, OutputPath = Tmp("out.mp3"), PreferredFormat = AudioFormat.Mp3 };
    private static string Tmp(string name) => Path.Combine(Path.GetTempPath(), "dominatus-elevenlabs-tests", Guid.NewGuid().ToString("N"), name);
    private static string Root() { var d = new DirectoryInfo(AppContext.BaseDirectory); while (d is not null && !File.Exists(Path.Combine(d.FullName, "Dominatus.slnx"))) d = d.Parent; return d!.FullName; }
    private sealed class FakeElevenLabsClient : IElevenLabsApiClient { public ElevenLabsSpeechRequest? Request; public ElevenLabsSpeechRequestOptions? Options; public byte[] AudioBytes = { 0x49, 0x44, 0x33 }; public Exception? Exception; public ValueTask<ElevenLabsSpeechResponse> CreateSpeechAsync(ElevenLabsSpeechRequest request, ElevenLabsSpeechRequestOptions options, CancellationToken cancellationToken) { Request = request; Options = options; if (Exception is not null) throw Exception; return new(new ElevenLabsSpeechResponse(AudioBytes, "audio/mpeg", "req-1")); } }
    private sealed class CaptureHandler : HttpMessageHandler { public string? ApiKey; public Uri? Uri; protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) { Uri = request.RequestUri; ApiKey = request.Headers.GetValues("xi-api-key").Single(); var json = await request.Content!.ReadAsStringAsync(cancellationToken); Assert.Contains("hello eleven", json); return new HttpResponseMessage(System.Net.HttpStatusCode.OK) { Content = new ByteArrayContent(new byte[] { 1, 2, 3 }) { Headers = { ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("audio/mpeg") } } }; } }
}
