<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Dominatus.Robotics.Quadcopter3D.Shared/Dominatus.Robotics.Quadcopter3D.Shared.csproj" />
  </ItemGroup>
</Project>
